language: node_js
before_install:
  - rvm install 2.3.1
  - gem install scss_lint
sudo: false
notifications:
  email: false
env:
  global:
    - CXX=g++-4.8
    - secure: "W7mi/0Hv7ssbTZ+bPTvIVmZ+AaqbMtmL9qlySXp1V293H5GF7u53v6Oom7BsJDtg3dkcVM2dZlc4mqRmuN2MNYyyndMdAcH7vD9UOA4Vy16vAv5FwdGBvaHwykT40lAf02OsQRFJZsMSpGtbLWnhJqRmIIDLtRycHUuKuf2dvwGJcxokt+PxfH38Siqk2TU8eQueK1vgcBXo/cvmeoBUc9HxnxrsfevK1dpUgSi5D5LlhzGSa3c+z/cD8QyLHH+OTTzTnoUuBTng6gV/GEcYgVRunVhtrRyrDF0siWH1Pg8CRqmxVsVUrehwCg+A6ZqsX9GjfeGZ88MjBXYU6mIVFEIeCVg5U6NyzPhjB/R7H5ktcoCswgP8SfwU/NZQ7EhWq+XQqZTCzxt1Qn2N6KFAWqa5V+ON7ujRP8spdHMHbAz/RwGkZ9+tHgWzPpNpRwdKNhuYFlRCiIXUmvqanDrfSE+5KPx1t2UWFTlSu/GOgUYQwVenA66JGSWffxNNZuA9qhjW+Li+iAXAkfFO9dJt0Mtcl5daO3Ks6twnPHshvENBDAVt4t2j2JBTf03XUBhaviYAVJT3GH8AR/FJpRCuIdQQg0DWH+woiNI5i82kypwC92cby8SlN+IOIMJ1F+x/IhFSqTVh28zsCf7Kf/19LdPEd1p0PNqnC32rDDiwNp8="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: ./script/test
after_script:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
